import { CARAVAN_RELEASES } from '@/fixtures/caravan/release';
import type { CoordinationState, Participant, ReleaseContext } from './types';

export const DEMO_SCOPE = 'firm:coordination-demo';
export const RELEASE_CONTEXTS: ReleaseContext[] = CARAVAN_RELEASES.map((release) => ({ domain: 'CARAVAN', releaseId: release.releaseId, buildId: release.build.buildId, knownAt: release.knownAt }));
const domains: Participant['domains'] = ['CARAVAN', 'TRADEWIND', 'LANDSHARK'];
const definition = (p: Pick<Participant, 'id' | 'name' | 'kind' | 'purpose' | 'authority' | 'inputs' | 'outputs' | 'capabilities' | 'reference'> & Partial<Participant>): Participant => ({ version: '0.1.0', runtime: 'JavaScript', status: 'REFERENCE', scope: DEMO_SCOPE, domains, ...p });

export const PARTICIPANTS: Participant[] = [
  definition({ id: 'apparatus.evidence', name: 'Evidence store', kind: 'APPARATUS', authority: 'evidence', purpose: 'Retain authorized source captures and immutable evidence references.', inputs: ['AuthorizedSource/v1'], outputs: ['EvidenceArtifact/v1'], capabilities: ['evidence.capture', 'evidence.resolve'], reference: 'Bench: src/authorized-acquisition-workflow.js; src/apparatus-workflow.js' }),
  definition({ id: 'apparatus.corpus', name: 'Domain corpus', kind: 'APPARATUS', authority: 'canonical', purpose: 'Build domain state and versioned corpora from admitted evidence and mappings.', inputs: ['NormalizedRecord/v1', 'IdentityMapping/v1'], outputs: ['CorpusBuild/v1'], capabilities: ['corpus.build', 'corpus.history'], reference: 'Bench: src/corpus-workflow.js; src/apparatus-workflow.js' }),
  definition({ id: 'apparatus.coordination', name: 'Payload OS coordination', kind: 'APPARATUS', authority: 'coordination', status: 'LOCAL', purpose: 'Register definitions and exchange requests, blockers, handoffs, results, and acknowledgements.', inputs: ['CoordinationMessage/v1'], outputs: ['CoordinationMessage/v1'], capabilities: ['stable.register', 'board.read', 'board.post', 'board.acknowledge'], reference: 'NotationsOS: src/coordination/' }),
  definition({ id: 'apparatus.compute', name: 'Computation apparatus', kind: 'APPARATUS', authority: 'derived', purpose: 'Reference boundary for computation over authorized context.', inputs: ['AuthorizedContext/v1'], outputs: ['AgentExecutionResult/v1'], capabilities: ['context.compute'], reference: 'Bench: src/agent-execution-workflow.js; managed execution absent' }),
  definition({ id: 'apparatus.delivery', name: 'API and feed projection', kind: 'APPARATUS', authority: 'projection', purpose: 'Distribute released records and changes within source rights.', inputs: ['CorpusRelease/v1', 'Retraction/v1'], outputs: ['DeliveredRecord/v1'], capabilities: ['release.read', 'feed.read', 'retraction.read'], reference: 'NotationsOS: src/adapter/feed.ts' }),
  definition({ id: 'apparatus.verification', name: 'Verification apparatus', kind: 'APPARATUS', authority: 'verification', purpose: 'Recompute declared checks and retain their scope and result.', inputs: ['CorpusBuild/v1'], outputs: ['VerificationEnvelope/v1'], capabilities: ['manifest.recompute'], reference: 'Bench: src/verification-router.js; independent verification absent here' }),
  definition({ id: 'agent.source', name: 'Source acquisition agent', kind: 'AGENT', authority: 'derived', runtime: 'Python', status: 'PLANNED', purpose: 'Acquire authorized material and hand evidence to normalization.', inputs: ['AuthorizedSource/v1'], outputs: ['EvidenceArtifact/v1'], capabilities: ['source.acquire'], reference: 'Planned wrapper around Bench source-acquisition contracts; connector absent' }),
  definition({ id: 'agent.normalize', name: 'Normalization agent', kind: 'AGENT', authority: 'derived', runtime: 'Python', status: 'PLANNED', purpose: 'Normalize extracted units, fields, and time with declared transforms.', inputs: ['EvidenceArtifact/v1'], outputs: ['NormalizedRecord/v1'], capabilities: ['record.normalize'], reference: 'Planned wrapper around Bench normalization workflow' }),
  definition({ id: 'agent.identity', name: 'Identity agent', kind: 'AGENT', authority: 'derived', runtime: 'Rust', status: 'PLANNED', purpose: 'Propose evidence-bearing mappings and expose unresolved identity.', inputs: ['NormalizedRecord/v1'], outputs: ['IdentityMapping/v1'], capabilities: ['identity.propose'], reference: 'Planned agent; authority to admit mappings remains with the corpus' }),
  definition({ id: 'agent.release', name: 'Release assembly agent', kind: 'AGENT', authority: 'derived', runtime: 'Rust', status: 'PLANNED', purpose: 'Assemble a release candidate from a build and verification references.', inputs: ['CorpusBuild/v1', 'VerificationEnvelope/v1'], outputs: ['CorpusRelease/v1'], capabilities: ['release.propose'], reference: 'Planned agent; posting a result does not activate a release' }),
  definition({ id: 'agent.recall', name: 'Correction and recall agent', kind: 'AGENT', authority: 'derived', runtime: 'Rust', status: 'PLANNED', purpose: 'Trace corrections through released records and propose recall notices.', inputs: ['CorpusRelease/v1', 'Correction/v1'], outputs: ['Retraction/v1'], capabilities: ['recall.propose'], reference: 'Planned wrapper around correction and recall contracts' }),
  definition({ id: 'agent.simulation', name: 'Simulation agent', kind: 'AGENT', authority: 'derived', runtime: 'C++', status: 'PLANNED', purpose: 'Run a bounded physical-system simulation over authorized inputs.', inputs: ['AuthorizedContext/v1', 'SimulationModel/v1'], outputs: ['SimulationResult/v1'], capabilities: ['simulation.propose'], reference: 'Planned definition; runtime and model execution absent' }),
];

/** Seed declarations are illustrative. No entry implies a deployed worker or running process. */
export function createSeed(): CoordinationState {
  const context = RELEASE_CONTEXTS.find((release) => release.releaseId === 'REL-CAR-2026.09.01')!;
  return structuredClone({
    schema: 'payload.coordination.v1', participants: PARTICIPANTS,
    messages: [
      { id: 'MSG-00001', sequence: 1, requestId: 'seed-1', scope: DEMO_SCOPE, authorId: 'apparatus.coordination', recipientId: null, kind: 'NOTE', topic: 'os-assembly', title: 'Assemble the Payload OS stable', body: 'Declare each apparatus and agent with its purpose, authority, inputs, outputs, and readiness. These entries are reference and planned definitions; this board launches no workers.', context: null, replyTo: null, createdAt: '2026-09-05T12:00:00.000Z' },
      { id: 'MSG-00002', sequence: 2, requestId: 'seed-2', scope: DEMO_SCOPE, authorId: 'apparatus.corpus', recipientId: 'agent.identity', kind: 'BLOCKER', topic: 'caravan-identity', title: 'Lot 7C-104 needs an evidence-bearing identity link', body: 'The demonstration release has no sample-to-lot link. Keep the identity unresolved; a board message alone cannot establish it.', context, replyTo: null, createdAt: '2026-09-05T12:05:00.000Z' },
      { id: 'MSG-00003', sequence: 3, requestId: 'seed-3', scope: DEMO_SCOPE, authorId: 'apparatus.verification', recipientId: 'agent.release', kind: 'HANDOFF', topic: 'release-assembly', title: 'Inspect the release manifest and internal recompute', body: 'The fixture manifest is available for inspection. Verification here is internal recompute. Record any proposed follow-up against this release and build.', context, replyTo: null, createdAt: '2026-09-05T12:10:00.000Z' },
    ], acknowledgements: [],
  });
}
