/**
 * The operating model, as data. The founder's statement is the authority
 * (docs/ECONOMIC_ARCHITECTURE.md); this module records it so the interface
 * can state what the firm is, what it makes, how it distributes it, whom it
 * serves, and what does and does not exist in this repository. Nothing here
 * is copy generated by the interface.
 */
import { DOMAINS, PRODUCT_ROOT } from './domains';
import { MATERIAL_CLASSES, MATERIAL_LABEL, PRODUCTION_STAGES, STAGE_LABEL, type MaterialClass, type ProductionStage } from './corpus';

export const THESIS = {
  firm: 'Notation Systems is a systems and intelligence firm for the physical economy. It builds computational representations of physical systems from authorized geospatial, remote-sensing, operational, and scientific source material.',
  production: 'Its internal production system turns that material into provenance-bearing computational corpora through acquisition, extraction, normalization, identity, ontology, computation, storage, indexing, verification, release, correction, and recall.',
  inventory: 'The corpora are the finished information inventory. APIs, feeds, reports, workbenches, and MCP tools distribute it. Customers apply their own inference, models, agents, and workflows to the data streams.',
  separation: 'Customer evidence, customer workloads, and proprietary-capital activity remain separated.',
  platform: 'Payload OS is the shared production layer, not a fourth customer API. Caravan, Tradewind, and Landshark are the bounded domain products.',
  layers: [
    { layer: 'Corpus + API / feed', role: 'The product' },
    { layer: 'Inference, model, agent', role: 'Customer computation, or hosted computation over authorized releases' },
    { layer: 'Ruling, admission profile, case workbench', role: 'Optional application layer over the corpus' },
  ],
} as const;

export const DISTRIBUTION_MECHANISMS = ['APIs', 'Feeds', 'Reports', 'Workbenches', 'MCP tools'] as const;

/** Where the shared machinery is actually implemented. This repository is a fixture-only product surface and workbench prototype over it. */
export const REFERENCE_IMPLEMENTATION = {
  name: 'Notations Bench',
  role: 'Reference implementation of the shared corpus, provenance, policy, release and verification machinery.',
  inThisRepository: 'Small TypeScript counterparts of its source-policy and evidence-capture workflows (src/data-os), used by the corpus layer and its tests. Not a second canonical Data OS.',
} as const;

export const CUSTOMER_CATEGORIES = [
  { id: 'brokers', title: 'Brokers', need: 'Rely on facts produced by other parties to move a transaction: quantities, conditions, custody, identity.' },
  { id: 'asset_managers', title: 'Asset and portfolio managers', need: 'Hold and re-evaluate positions against point-in-time state, with corrections and recalls pushed rather than discovered.' },
  { id: 'insurance_financing', title: 'Insurance and financing firms', need: 'Underwrite and lend against evidence whose provenance, bounds and rights survive downstream use and audit.' },
] as const;

/** The economic architecture, in order. */
export const ECONOMIC_ARCHITECTURE = [
  { step: 1, statement: 'Build governed computational corpora', inThisRepository: 'Corpus releases with production records, certification and rights (fixture); the local candidate rail before admission (present, unadmitted).' },
  { step: 2, statement: 'Distribute them as data systems and products', inThisRepository: 'Feed API, stream, retractions, MCP tools, the Caravan workbench (fixture).' },
  { step: 3, statement: 'Host compute over authorized corpus releases', inThisRepository: 'Release-bound execution context in every answer; managed execution absent.' },
  { step: 4, statement: 'Separately govern any proprietary trading/speculation activity', inThisRepository: 'Recorded as governance and as prohibited uses in every rights schedule; no such activity here.' },
] as const;

export type Presence = 'PRESENT' | 'FIXTURE' | 'POLICY_ONLY' | 'ABSENT';

export const PRESENCE_LABEL: Record<Presence, string> = {
  PRESENT: 'Present',
  FIXTURE: 'Present as demonstration fixture',
  POLICY_ONLY: 'Recorded as policy only',
  ABSENT: 'Absent',
};

export interface Engine {
  id: 'data_systems' | 'compute';
  title: string;
  description: string;
  inThisRepository: Array<{ item: string; presence: Presence; where?: string }>;
}

export const ENGINES: readonly Engine[] = [
  {
    id: 'data_systems',
    title: 'Data systems and products',
    description: 'Computational corpora distributed as APIs, feeds, reports, workbenches and MCP tools, and vertical applications built on them.',
    inThisRepository: [
      { item: 'Corpus releases with production records, release digests and certified release manifests', presence: 'FIXTURE', where: '/releases' },
      { item: 'Records with uncertainty and validity bounds, both clocks, provenance, evidence class, rights and identity', presence: 'FIXTURE', where: '/stream' },
      { item: 'As-of answers and typed refusals', presence: 'FIXTURE', where: '/api/v1/releases/REL-CAR-2026.09.01/as-of?subject=LOT-5B-221&predicate=quantity.gross&validAt=2026-08-17T16:00:00Z&knownAt=2026-09-01T12:00:00Z' },
      { item: 'Push retractions: corrections and recalls', presence: 'FIXTURE', where: '/retractions' },
      { item: 'Feed API', presence: 'FIXTURE', where: '/api' },
      { item: 'MCP tools over the same feed', presence: 'FIXTURE', where: '/api#api-mcp' },
      { item: 'Source-use policy and evidence capture contracts (data-os, Bench-derived)', presence: 'PRESENT', where: '/api#api-vocab' },
      { item: 'Local candidate-production rail: evidence intake, Carrier normalization, time-bounded candidate builds; every record UNADMITTED and outside the feed', presence: 'PRESENT', where: '/candidates' },
      { item: 'Reports', presence: 'ABSENT' },
      { item: 'Decision workbench (Caravan ruling application)', presence: 'FIXTURE', where: '/cases' },
      { item: 'Small Rust notation state kernel: local authored objects, undo/redo and frontend save/reload; not canonical corpus state', presence: 'PRESENT', where: '/notations' },
      { item: 'One bounded live source connector: FMCSA Company Census, operator-only internal qualification; no customer redistribution or canonical admission', presence: 'PRESENT' },
      { item: 'FMCSA typed normalization and exact-reference v2 candidate builds over retained captures: operator CLI only, UNADMITTED, outside customer feeds', presence: 'PRESENT' },
      { item: 'Samsara single-vehicle GPS-history adapter: operator-only, offline-tested; live fleet qualification, continuous sync and inferred visits remain absent', presence: 'PRESENT' },
      { item: 'Production source fleet, recurring ingestion and customer-released live data', presence: 'ABSENT' },
      { item: 'Production storage and identity', presence: 'ABSENT' },
      { item: 'Deployed customer delivery', presence: 'ABSENT' },
      { item: 'Independent verification', presence: 'ABSENT' },
      { item: 'A completed pilot', presence: 'ABSENT' },
    ],
  },
  {
    id: 'compute',
    title: 'Hosted compute over authorized corpus releases',
    description: 'Customer models, simulations, agents and workloads executed against authorized releases without losing lineage, policy or recallability.',
    inThisRepository: [
      { item: 'Release-bound execution context: every answer names its release, build, both clocks and bounds so a workload can cite them', presence: 'FIXTURE', where: '/api' },
      { item: 'Local instruments only: pinned GAT IFC audit and evidence-bound observation replay; not managed customer workloads', presence: 'PRESENT' },
      { item: 'Local scalar linear-Gaussian benchmark: evidence-linked model results and separate held-out-reference metrics; synthetic demonstration, not field validation', presence: 'PRESENT' },
      { item: 'Local weighted rigid registration and explicit Euclidean/access-network distances: evidence-bound CLI and synthetic inspector; not physical validation or live routing', presence: 'PRESENT', where: '/compute/registration' },
      { item: 'Local clearance value-of-information experiment: exact joint beliefs, hypothetical measurement comparison and evidence-bound runs; not active inference, independent calibration or action execution', presence: 'PRESENT', where: '/compute/clearance' },
      { item: 'Trained neural models and independently validated physical prediction', presence: 'ABSENT' },
      { item: 'Managed execution of customer workloads', presence: 'ABSENT' },
    ],
  },
];

export const PRODUCTION_SYSTEM: ReadonlyArray<{ stage: ProductionStage; label: string; meaning: string }> = PRODUCTION_STAGES.map((stage) => ({
  stage,
  label: STAGE_LABEL[stage],
  meaning: {
    acquisition: 'Authorized source material read under its licence and content-addressed on ingest.',
    extraction: 'Bounded fields extracted from each artifact; raw bytes stay in the evidence store.',
    normalization: 'Units, names, locations and temporal fields normalized; the transform version recorded as lineage.',
    identity: 'Ambiguous mentions kept as candidates; a subject reaches another only through evidence. Similarity never merges.',
    ontology: 'Predicates aligned to a declared, versioned vocabulary.',
    computation: 'Derived quantities computed by named, versioned methods, distinguishable from observed ones.',
    storage: 'Canonical state written to the release store with both clocks, bounds, evidence class, rights and stable identity.',
    indexing: 'Subject, predicate and time indexes for as-of queries.',
    verification: 'Records recomputed and compared; the state of verification stated, never overclaimed.',
    release: 'A release manifest produced and committed; its commitment travels with the release.',
    correction: 'A superseding record issued against a release; earlier releases left as they stood.',
    recall: 'A record or release withdrawn, with everything downstream that relied on it named.',
  }[stage],
}));

export const MATERIAL_CLASSES_IN_CORPUS: ReadonlyArray<{ materialClass: MaterialClass; label: string; presentInDemo: boolean }> = MATERIAL_CLASSES.map((m) => ({
  materialClass: m,
  label: MATERIAL_LABEL[m],
  presentInDemo: m === 'operational' || m === 'scientific',
}));

export const VALUE_PROPOSITION = [
  '"As-of" answers that reconstruct what was knowable at a specific time.',
  'Machine-readable uncertainty and validity bounds, not footnotes.',
  'Certified release manifests and push retractions when a fact changes.',
  'Provenance that survives downstream use, audit, and resale.',
  'A customer can automate a decision against the feed without blindly trusting a black box.',
] as const;

export const PRODUCT_ARCHITECTURE = { ...PRODUCT_ROOT, domains: DOMAINS } as const;
