/**
 * The operating model, as data. The founder's statement of the economic
 * architecture is the authority (docs/ECONOMIC_ARCHITECTURE.md); this
 * module records it so the interface can state what the firm makes, how it
 * distributes it, and what does and does not exist in this repository.
 * Nothing here is marketing copy generated by the interface.
 */
import { DOMAINS } from './domains';
import { PRODUCTION_STAGES, STAGE_LABEL, type ProductionStage } from './corpus';

export const THESIS = {
  statement: 'Notation Systems is an information manufacturer. It turns heterogeneous source material into governed, point-in-time, computable corpus releases; products and infrastructure distribute and execute against those releases.',
  concise: 'Notation Systems builds provenance-bearing computational corpora, exposes them as durable data streams and APIs, and operates the compute systems that make those corpora useful.',
  finishedGood: 'The customer-facing API, feed, report, agent, or workbench is not the finished good itself; it is the distribution mechanism for a certified corpus release.',
  layers: [
    { layer: 'Corpus + API / feed', role: 'The product' },
    { layer: 'Inference, model, agent', role: 'Customer computation, or hosted computation on customer authority' },
    { layer: 'Ruling, admission profile, case workbench', role: 'Optional application layer over the corpus' },
  ],
} as const;

export type Presence = 'PRESENT' | 'FIXTURE' | 'POLICY_ONLY' | 'ABSENT';

export interface Engine {
  id: 'data_systems' | 'compute';
  title: string;
  description: string;
  distribution: string[];
  inThisRepository: Array<{ item: string; presence: Presence; where?: string }>;
}

export const ENGINES: readonly Engine[] = [
  {
    id: 'data_systems',
    title: 'Data systems and intelligence products',
    description: 'Notation Systems licenses computational corpora, APIs, feeds, decision workbenches, reports, and vertical applications built on those corpora.',
    distribution: ['Computational corpora', 'APIs', 'Feeds', 'Decision workbenches', 'Reports', 'Vertical applications'],
    inThisRepository: [
      { item: 'Corpus releases with build records, release digests and certified release manifests', presence: 'FIXTURE', where: '/releases' },
      { item: 'Records with uncertainty and validity bounds, both clocks, provenance, evidence class, rights and identity', presence: 'FIXTURE', where: '/stream' },
      { item: 'As-of answers and typed refusals', presence: 'FIXTURE', where: '/api/v1/releases/:id/as-of' },
      { item: 'Push retractions', presence: 'FIXTURE', where: '/retractions' },
      { item: 'Feed API', presence: 'FIXTURE', where: '/api' },
      { item: 'Decision workbench (Caravan ruling application)', presence: 'FIXTURE', where: '/cases' },
      { item: 'Live source connectors, production storage and identity, deployed customer delivery, a completed pilot', presence: 'ABSENT' },
    ],
  },
  {
    id: 'compute',
    title: 'Provenance-preserving compute',
    description: 'The firm operates managed storage, models, simulations, agents, and computational workloads over authorized corpus releases, allowing customers to execute confidential work without losing lineage, policy, or recallability.',
    distribution: ['Managed storage', 'Models', 'Simulations', 'Agents', 'Computational workloads over authorized releases'],
    inThisRepository: [
      { item: 'Release-bound execution context: every feed answer names its release, build and both clocks so a workload can cite them', presence: 'FIXTURE', where: '/api' },
      { item: 'Managed execution of customer workloads', presence: 'ABSENT' },
    ],
  },
];

export const PRINCIPAL_CAPITAL = {
  title: 'Separately governed principal-capital activity',
  framing: 'Over time, a separately governed principal-capital activity may deploy the firm\'s own capital using lawfully acquired and policy-permitted proprietary intelligence. This activity is distinct from customer products: it has separate information-access controls, capital allocation, risk management, reporting, and conflict governance. Customer evidence remains tenant-isolated; customer workloads remain confidential; proprietary strategies cannot draw on restricted customer information.',
  rules: ['Explicit non-use rules in every rights schedule', 'Licensing that names permitted uses', 'Release-timing rules', 'An information barrier'],
  presence: 'POLICY_ONLY' as Presence,
  note: 'Not an activity of this repository. Recorded as governance on the corpus and as prohibited uses in every rights schedule.',
};

export const PRODUCTION_SYSTEM: ReadonlyArray<{ stage: ProductionStage; label: string; meaning: string }> = PRODUCTION_STAGES.map((stage) => ({
  stage,
  label: STAGE_LABEL[stage],
  meaning: {
    source_acquisition: 'Authorized source material read under its licence and content-addressed on ingest.',
    normalization: 'Units, names, locations and temporal fields normalized; the transform version recorded as lineage.',
    identity_resolution: 'Ambiguous mentions kept as candidates; a subject reaches another only through evidence. Similarity never merges.',
    ontology_alignment: 'Predicates aligned to a declared, versioned vocabulary.',
    canonical_state: 'Domain-bounded canonical state: records with both clocks, bounds, evidence class, rights and stable identity.',
    scientific_computation: 'Derived quantities computed by named, versioned methods, distinguishable from observed ones.',
    indexing: 'Subject, predicate and time indexes for as-of queries.',
    verification: 'Records recomputed and compared; the state of verification stated, never overclaimed.',
    release_certification: 'A release manifest produced and committed; its commitment travels with the release.',
    correction: 'Retractions issued against a release; earlier releases left as they stood.',
  }[stage],
}));

export const VALUE_PROPOSITION = [
  '"As-of" answers that reconstruct what was knowable at a specific time.',
  'Machine-readable uncertainty and validity bounds, not footnotes.',
  'Certified release manifests and push retractions when a fact changes.',
  'Provenance that survives downstream use, audit, and resale.',
  'A customer can automate a decision against the feed without blindly trusting a black box.',
] as const;

export const DOMAIN_PRODUCTS = DOMAINS;

export const PRESENCE_LABEL: Record<Presence, string> = {
  PRESENT: 'Present',
  FIXTURE: 'Present as demonstration fixture',
  POLICY_ONLY: 'Recorded as policy only',
  ABSENT: 'Absent',
};
