import { test, expect } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';

test('notations: real local state preserves navigation drafts and survives Rust undo and save/page reload', async ({ page }, testInfo) => {
  test.skip(process.env.STATE_KERNEL_E2E !== '1', 'Requires the enabled, isolated local state-kernel server; no browser API mocking.');
  const errors: string[] = [];
  let stateReads = 0;
  page.on('pageerror', (error) => errors.push(error.message));
  page.on('request', (request) => {
    if (new URL(request.url()).pathname === '/api/state-kernel' && request.method() === 'GET') stateReads++;
  });
  await page.goto('/notations');
  await expect(page.getByRole('heading', { level: 1, name: 'Notations', exact: true })).toBeVisible();
  await expect(page.getByText('Saved local state loaded.', { exact: true })).toBeVisible();
  await expect(page.getByText('LOCAL DEVELOPMENT', { exact: true })).toBeVisible();
  const initialVersion = Number(await page.getByTestId('saved-version').textContent());
  const title = `Local notation ${testInfo.project.name} ${Date.now()}`;
  await page.getByLabel('New notation title', { exact: true }).fill(title);
  await page.getByLabel('New notation body', { exact: true }).fill('Original authored notation, not canonical evidence.');
  await page.getByRole('button', { name: 'Preview new notation', exact: true }).click();
  await expect(page.getByTestId('pending-count')).toHaveText('1');
  const notationId = await page.getByTestId('selected-notation-id').textContent();
  expect(notationId).toMatch(/^[a-f0-9-]{36}$/);
  await expect(page.getByTestId('saved-version')).toHaveText(String(initialVersion));
  await page.getByLabel('Notation title', { exact: true }).fill(`${title} revised`);
  await page.getByLabel('Notation body', { exact: true }).fill('Revised authored local context.');
  await page.getByLabel('New notation title', { exact: true }).fill('Unapplied navigation draft');
  await page.getByLabel('New notation body', { exact: true }).fill('Keep this typed text across routes.');
  await page.getByLabel('Relation label', { exact: true }).fill('Unapplied relation');
  await page.getByRole('navigation', { name: 'Primary' }).getByRole('link', { name: 'Releases', exact: true }).click();
  await expect(page).toHaveURL(/\/releases$/);
  await expect(page.getByRole('region', { name: 'What a release is', exact: true })).toBeVisible();
  expect(await page.evaluate(() => {
    const event = new Event('beforeunload', { cancelable: true });
    window.dispatchEvent(event);
    return event.defaultPrevented;
  })).toBe(true);
  await page.getByRole('navigation', { name: 'Primary' }).getByRole('link', { name: 'Notations', exact: true }).click();
  await expect(page).toHaveURL(/\/notations$/);
  await expect(page.getByTestId('selected-notation-id')).toHaveText(notationId!);
  await expect(page.getByTestId('pending-count')).toHaveText('1');
  await expect(page.getByTestId('saved-version')).toHaveText(String(initialVersion));
  await expect(page.getByLabel('Notation title', { exact: true })).toHaveValue(`${title} revised`);
  await expect(page.getByLabel('Notation body', { exact: true })).toHaveValue('Revised authored local context.');
  await expect(page.getByLabel('New notation title', { exact: true })).toHaveValue('Unapplied navigation draft');
  await expect(page.getByLabel('New notation body', { exact: true })).toHaveValue('Keep this typed text across routes.');
  await expect(page.getByLabel('Relation label', { exact: true })).toHaveValue('Unapplied relation');
  expect(stateReads).toBe(1);
  await page.getByRole('button', { name: 'Clear new notation', exact: true }).click();
  await page.getByRole('button', { name: 'Clear relation form', exact: true }).click();
  await page.getByRole('button', { name: 'Preview changes', exact: true }).click();
  await expect(page.getByTestId('pending-count')).toHaveText('2');
  await expect(page.getByTestId('selected-notation-id')).toHaveText(notationId!);
  await page.getByRole('button', { name: 'Undo', exact: true }).click();
  await expect(page.getByLabel('Notation title', { exact: true })).toHaveValue(title);
  await expect(page.getByLabel('Notation body', { exact: true })).toHaveValue('Original authored notation, not canonical evidence.');
  await expect(page.getByTestId('pending-count')).toHaveText('3');
  await page.getByRole('button', { name: 'Save local version', exact: true }).click();
  await expect(page.getByText(`Saved local version ${initialVersion + 1}.`, { exact: true })).toBeVisible();
  await expect(page.getByTestId('pending-count')).toHaveText('0');
  await page.reload();
  await expect(page.getByText('Saved local state loaded.', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: `Select notation ${title}`, exact: true }).click();
  await expect(page.getByTestId('selected-notation-id')).toHaveText(notationId!);
  await expect(page.getByLabel('Notation title', { exact: true })).toHaveValue(title);
  await expect(page.getByLabel('Notation body', { exact: true })).toHaveValue('Original authored notation, not canonical evidence.');
  await expect(page.getByTestId('saved-version')).toHaveText(String(initialVersion + 1));
  await expect(page.getByRole('button', { name: 'Redo', exact: true })).toBeEnabled();
  const dimensions = await page.evaluate(() => ({ content: document.documentElement.scrollWidth, viewport: window.innerWidth }));
  expect(dimensions.content).toBeLessThanOrEqual(dimensions.viewport + 1);
  const accessibility = await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag22aa']).analyze();
  expect(accessibility.violations.filter((violation) => violation.impact === 'serious' || violation.impact === 'critical')).toEqual([]);
  expect(errors).toEqual([]);
  await page.evaluate(() => window.scrollTo({ top: 0, left: 0, behavior: 'instant' }));
  await page.screenshot({ path: testInfo.outputPath('notation-state.png'), fullPage: true });
});
